# Generated by Django 4.0.4 on 2022-05-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpermissionlist',
            old_name='permission_list',
            new_name='permissions_list',
        ),
    ]
