# Generated by Django 4.0.4 on 2022-06-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
