# Generated by Django 4.0.4 on 2022-04-26 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_created_by_alter_user_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='teamusers',
            new_name='team_users',
        ),
    ]
