# Generated by Django 4.0.4 on 2022-04-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_team_deleted_at_alter_user_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sdfdsfd',
            field=models.JSONField(default=None),
        ),
    ]
