# Generated by Django 4.0.4 on 2022-06-13 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(related_name='notifications', through='users.UserNotification', to=settings.AUTH_USER_MODEL),
        ),
    ]
