# Generated by Django 4.0.4 on 2022-06-01 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_permission_list_userpermissionlist_permissions_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='model',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
