# Generated by Django 4.0.4 on 2022-06-13 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(related_name='user_notifications', through='users.UserNotification', to=settings.AUTH_USER_MODEL),
        ),
    ]
