# Generated by Django 4.0.4 on 2022-05-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_teamusers_team_team_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
