# Generated by Django 4.0.4 on 2022-06-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_created_at_role_created_by_role_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='user',
            new_name='users',
        ),
    ]
