# Generated by Django 4.0.4 on 2022-06-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_action_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamuser',
            unique_together={('team', 'user')},
        ),
    ]
