# Generated by Django 4.0.4 on 2022-04-24 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_team_created_by_team_updated_by_user_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='project',
        ),
        migrations.AddField(
            model_name='team',
            name='teamusers',
            field=models.ManyToManyField(through='users.TeamUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
