# Generated by Django 4.0.4 on 2022-08-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='proles',
        ),
    ]
