# Generated by Django 4.0.4 on 2022-04-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_project_team_teamusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('notify', 'Notify'), ('error', 'Error'), ('success', 'Success'), ('warning', 'Warning')], default='notify', max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='reminder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
