# Generated by Django 4.0.4 on 2022-06-14 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_notification_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='users.notification'),
        ),
    ]
