# Generated by Django 4.0.4 on 2022-05-19 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_users',
            field=models.ManyToManyField(related_name='team_users', through='users.TeamUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
