# Generated by Django 4.0.4 on 2022-05-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_team_team_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamuser',
            name='type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
