# Generated by Django 4.0.4 on 2022-06-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usernotification_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
