# Generated by Django 4.0.4 on 2022-05-19 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_teamuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_users',
            field=models.ManyToManyField(through='users.TeamUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
