# Generated by Django 4.0.4 on 2022-05-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_team_team_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamuser',
            old_name='type',
            new_name='position',
        ),
        migrations.AddField(
            model_name='teamuser',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
