# Generated by Django 4.0.4 on 2022-06-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usernotification_model_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotification',
            old_name='model_id',
            new_name='instance_id',
        ),
    ]
