# Generated by Django 4.0.4 on 2022-05-20 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_type_teamuser_position_teamuser_is_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_users',
        ),
        migrations.AddField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(related_name='users', through='users.TeamUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
