# Generated by Django 4.0.4 on 2022-05-21 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='deleted_at',
        ),
        migrations.DeleteModel(
            name='UserNote',
        ),
    ]
