# Generated by Django 4.0.4 on 2022-05-23 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_phone_user_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(related_name='%(class)ss', through='users.TeamUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
