# Generated by Django 4.0.4 on 2022-05-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_reminder_remind_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='remind_at',
        ),
    ]
