# Generated by Django 4.0.4 on 2022-05-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_reminder_remind_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='remind_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
