# Generated by Django 4.0.4 on 2022-05-30 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_teamuser_team_alter_teamuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('codename', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SubAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='permission', to='users.action')),
                ('role', models.ManyToManyField(
                    related_name='roles_permissions', to='users.role')),
                ('user', models.ManyToManyField(
                    related_name='users_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='subaction',
            field=models.ManyToManyField(
                related_name='sub_actions', to='users.subaction'),
        ),
    ]
