# Generated by Django 4.0.4 on 2022-05-30 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_action_role_subaction_permission_action_subaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_action', to='users.action'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='role',
            field=models.ManyToManyField(related_name='permissions_role', to='users.role'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='user',
            field=models.ManyToManyField(related_name='permissions_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
