# Generated by Django 4.0.4 on 2022-05-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_permission_action_alter_permission_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='role',
            field=models.ManyToManyField(related_name='permissions_roles', to='users.role'),
        ),
    ]
