# Generated by Django 4.0.4 on 2022-04-24 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('p_start_date', models.DateTimeField()),
                ('p_end_date', models.DateTimeField()),
                ('a_start_date', models.DateTimeField()),
                ('a_end_date', models.DateTimeField()),
                ('banner', models.CharField(max_length=120)),
                ('status', models.IntegerField()),
                ('progress', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('project_details', models.JSONField()),
                ('company_name', models.CharField(max_length=100)),
                ('company_location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
