# Generated by Django 4.0.4 on 2022-06-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='size',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
