# Generated by Django 4.0.4 on 2022-06-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.CharField(choices=[('initial_cost', 'Initial Cost'), ('maintenance', 'Maintenance'), ('upgrades', 'Upgrades'), ('sales', 'Sales'), ('donates', 'Donates'), ('other', 'Other')], default='initial_cost', max_length=24),
        ),
    ]
