# Generated by Django 4.0.4 on 2022-07-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
