# Generated by Django 4.0.4 on 2022-06-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
