# Generated by Django 4.0.4 on 2022-06-18 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_rename_model_id_usernotification_instance_id'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prole_created_by', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(related_name='projects_roles', to='projects.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prole_updated_by', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='prole_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_action', to='users.action')),
                ('proles', models.ManyToManyField(related_name='permissions_roles', to='projects.projectrole')),
                ('sub_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_sub_action', to='users.subaction')),
            ],
        ),
    ]
