# Generated by Django 4.0.4 on 2022-06-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_delete_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='city', max_length=128),
            preserve_default=False,
        ),
    ]
