# Generated by Django 4.0.4 on 2022-06-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectrole_projectpermission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectUserPermissionList',
        ),
    ]
