# Generated by Django 4.0.4 on 2022-06-09 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_location_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_location', to='projects.project'),
        ),
    ]
