# Generated by Django 4.0.4 on 2022-06-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_location_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='city',
        ),
    ]
