# Generated by Django 4.0.4 on 2022-07-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_income_date_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='project_banners'),
        ),
    ]
