# Generated by Django 4.0.4 on 2022-07-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='a_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='a_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
