# Generated by Django 4.0.4 on 2022-04-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
