# Generated by Django 4.0.4 on 2022-04-24 10:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_delete_projectattachment_alter_attachement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('amount', models.FloatField()),
                ('type', models.CharField(choices=[('initial_cost', 'Initial Cost'), ('maintanance', 'Maintanance'), ('upgrades', 'Upgrades')], default='initial_cost', max_length=24)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('bank_transaction', 'Bank Transaction')], default='cash', max_length=24)),
                ('income', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.income')),
            ],
        ),
    ]
