# Generated by Django 4.0.4 on 2022-08-03 05:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_position'),
        ('projects', '0007_alter_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_action', to='users.action')),
                ('project_roles', models.ManyToManyField(related_name='permissions_roles', to='projects.projectrole')),
                ('sub_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_sub_action', to='users.subaction')),
            ],
        ),
    ]
