# Generated by Django 4.0.4 on 2022-05-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_a_end_date_alter_project_a_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='banner',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
