# Generated by Django 4.0.4 on 2022-04-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_income_payments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
