# Generated by Django 4.0.4 on 2022-06-22 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projectcategory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcategory',
            name='parent',
        ),
    ]
