# Generated by Django 4.0.4 on 2022-05-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_project_details'),
        ('projects', '0008_alter_project_banner_alter_project_status'),
    ]

    operations = [
    ]
