# Generated by Django 4.0.4 on 2022-08-03 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_permission_proles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_projectpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpermission',
            name='project_roles',
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_role', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='users',
            field=models.ManyToManyField(related_name='project_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProjectRole',
        ),
    ]
