# Generated by Django 4.0.4 on 2022-05-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_teamusers_team_team_users'),
        ('projects', '0009_merge_20220516_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(related_name='project_team', to='users.team'),
        ),
    ]
