# Generated by Django 4.0.4 on 2022-06-22 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_projectcategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_category', to='projects.projectcategory'),
        ),
    ]
