# Generated by Django 4.0.4 on 2022-08-03 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_projectpermission_project_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpermission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_role', to='projects.project'),
        ),
    ]
