# Generated by Django 4.0.4 on 2022-08-03 10:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_projectpermission_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('codename', models.CharField(max_length=64, unique=True)),
                ('model', models.CharField(max_length=64, unique=True)),
                ('order', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_action', to='projects.action'),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='sub_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_sub_action', to='projects.subaction'),
        ),
    ]
