# Generated by Django 4.0.4 on 2022-05-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[], default='normal', max_length=24),
        ),
    ]
