# Generated by Django 4.0.4 on 2022-08-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_action_subaction_alter_projectpermission_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='focalpoint',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='focalpoint_profiles'),
        ),
    ]
