# Generated by Django 4.0.4 on 2022-05-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
