# Generated by Django 4.0.4 on 2022-06-23 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_category_project_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='department',
            new_name='departments',
        ),
    ]
