# Generated by Django 4.0.4 on 2022-09-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_focalpoint_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='amount',
        ),
    ]
