# Generated by Django 4.0.4 on 2022-05-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company_email',
            field=models.EmailField(max_length=254),
        ),
    ]
