# Generated by Django 4.0.4 on 2022-05-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('1', 'Critical'), ('2', 'Very Important'), ('3', 'Important'), ('4', 'Normal'), ('5', 'Less Important')], default=4, max_length=24),
        ),
    ]
