# Generated by Django 4.0.4 on 2022-05-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
