# Generated by Django 4.0.4 on 2022-06-23 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_department_deleted_by_focalpoint_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='stage',
            name='departments',
        ),
        migrations.AddField(
            model_name='stage',
            name='departments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_stages', to='projects.department'),
        ),
    ]
