# Generated by Django 4.0.4 on 2022-06-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_department_description_remove_stage_departments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='departments',
            new_name='department',
        ),
    ]
