# Generated by Django 4.0.4 on 2022-05-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_project_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Very Important', 'Very Important'), ('Important', 'Important'), ('Normal', 'Normal'), ('Less Important', 'Less Important')], default='normal', max_length=24),
        ),
    ]
