# Generated by Django 4.0.4 on 2022-06-23 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_stage_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='projects.department'),
        ),
    ]
