# Generated by Django 4.0.4 on 2022-06-23 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_stage_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substage',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_stages', to='projects.stage'),
        ),
    ]
