# Generated by Django 4.0.4 on 2022-06-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_substage_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substage',
            name='task',
        ),
    ]
