# Generated by Django 4.0.4 on 2022-05-18 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_test_arttest_researchtest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchtest',
            name='test_ptr',
        ),
        migrations.RemoveField(
            model_name='test',
            name='polymorphic_ctype',
        ),
        migrations.DeleteModel(
            name='ArtTest',
        ),
        migrations.DeleteModel(
            name='ResearchTest',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
