# Generated by Django 4.0.4 on 2022-06-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_substage_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='a_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='a_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
