# Generated by Django 4.0.4 on 2022-05-18 05:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_researchtest_test_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='object_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='reason',
            name='object_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
