# Generated by Django 4.0.4 on 2022-05-18 05:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_attachment_object_id_alter_reason_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='object_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='reason',
            name='object_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
