# Generated by Django 4.0.4 on 2022-06-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_project_a_end_date_alter_project_a_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
