# Generated by Django 4.0.4 on 2022-05-19 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_alter_project_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company_location',
        ),
        migrations.AddField(
            model_name='location',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
