# Generated by Django 4.0.4 on 2022-05-19 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_remove_project_company_location_location_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_location', to='projects.project'),
        ),
    ]
