# Generated by Django 4.0.4 on 2022-05-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_alter_location_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="address_line_one",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="address_line_two",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="state",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
