# Generated by Django 4.0.4 on 2022-05-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_type_teamuser_position_teamuser_is_leader'),
        ('projects', '0029_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(related_name='team_projects', to='users.team'),
        ),
    ]
