# Generated by Django 4.0.4 on 2022-05-23 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_phone_user_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0031_alter_project_a_end_date_alter_project_a_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(related_name='teams', to='users.team'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='project_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
