# Generated by Django 4.0.4 on 2022-05-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_phone_user_whatsapp'),
        ('projects', '0032_alter_project_teams_alter_project_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(related_name='projects', to='users.team'),
        ),
    ]
