# Generated by Django 4.0.4 on 2022-05-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_phone_user_whatsapp'),
        ('projects', '0033_alter_project_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(related_name='%(class)s', to='users.team'),
        ),
    ]
