# Generated by Django 4.0.4 on 2022-05-30 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_alter_focalpoint_contact_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='path',
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachement',
            field=models.FileField(default=django.utils.timezone.now, upload_to='attachements'),
            preserve_default=False,
        ),
    ]
