# Generated by Django 4.0.4 on 2022-05-30 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_remove_attachment_path_attachment_attachement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='attachement',
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(default=django.utils.timezone.now, upload_to='attachments'),
            preserve_default=False,
        ),
    ]
