# Generated by Django 4.0.4 on 2022-05-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_remove_attachment_attachement_attachment_attachment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['content_type', 'object_id'], name='projects_at_content_b96819_idx'),
        ),
    ]
