# Generated by Django 4.0.4 on 2022-05-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_attachment_projects_at_content_b96819_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reason',
            index=models.Index(fields=['content_type', 'object_id'], name='projects_re_content_bf70f3_idx'),
        ),
    ]
