# Generated by Django 4.0.4 on 2022-04-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='coast',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='cpp',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
