# Generated by Django 4.0.4 on 2022-05-21 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_alter_project_teams'),
        ('expenses', '0004_rename_coast_expense_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='projects.project'),
        ),
    ]
