# Generated by Django 4.0.4 on 2022-05-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expense_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='cost',
        ),
    ]
