# Generated by Django 4.0.4 on 2022-05-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_expenseitem_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenseitem',
            old_name='cpp',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='expenseitem',
            old_name='item',
            new_name='name',
        ),
    ]
