# Generated by Django 4.0.4 on 2022-05-26 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_rename_cpp_expenseitem_cost_and_more'),
        ('expenses', '0009_rename_cpp_expenseitem_cost_and_more'),
    ]

    operations = [
    ]
