# Generated by Django 4.0.4 on 2022-06-28 09:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=64, null=True)),
                ('company_name', models.CharField(blank=True, max_length=128, null=True)),
                ('industry', models.CharField(blank=True, max_length=128, null=True)),
                ('hear_about_us', models.CharField(blank=True, choices=[('search_engine', 'Search Engine'), ('google_ads', 'Google Ads'), ('facebook_ads', 'Facebook Ads'), ('instagram_ads', 'Instagram Ads'), ('youtube_ads', 'Youtube Ads'), ('linkedin_ads', 'Linkedin Ads'), ('snapchat_ads', 'Snapchat Ads'), ('twitter_ads', 'Twitter Ads'), ('tiktok_ads', 'Tiktok Ads'), ('ther_social_media_ads', 'Other Social Media Ads'), ('email', 'Email'), ('radio', 'Radio'), ('TV', 'Tv'), ('newspaper', 'Newspaper'), ('word_of_mouth', 'Word Of Mouth'), ('other', 'Other')], max_length=64, null=True)),
                ('lead_type', models.CharField(blank=True, choices=[('manual', 'Manual'), ('website', 'Website'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'Linkedin'), ('youtube', 'Youtube'), ('tiktok', 'Tiktok'), ('whatsapp', 'Whatsapp'), ('other', 'Other')], max_length=64, null=True)),
                ('prefer_com_way', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'Whatsapp')], max_length=32, null=True)),
                ('is_requirement_ready', models.BooleanField(default=False)),
                ('need_for_demo', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('need_to_communicate', 'Need To Communicate'), ('not_interested', 'Not Interested'), ('not_answered', 'Not Answered'), ('not_interested_now', 'Not Interest Now'), ('incorrect_contact', 'Incorrect Contact'), ('check_and_come_back', 'Check And Come Back'), ('understood_wrong', 'Understood Wrong'), ('confirm', 'Confirm')], default='pending', max_length=32)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(blank=True, max_length=32, null=True)),
                ('on_request_price', models.FloatField(blank=True, max_length=255, null=True)),
                ('on_request_date', models.DateTimeField(blank=True, null=True)),
                ('purchased_price', models.FloatField(blank=True, max_length=255, null=True)),
                ('purchased_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(blank=True, max_length=128, null=True)),
                ('plan_price', models.FloatField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('developed_by', models.CharField(blank=True, max_length=128, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'Review'), ('confirm', 'Confirm'), ('reject', 'Reject'), ('miss_info', 'Miss Info')], default='pending', max_length=32)),
                ('goals_and_expectation', models.TextField(blank=True, null=True)),
                ('budget', models.FloatField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=32, null=True)),
                ('project_timeline', models.CharField(blank=True, max_length=255, null=True)),
                ('frequently_of_receive_progress_report', models.TextField(blank=True, null=True)),
                ('what_are_we_delivering', models.TextField(blank=True, null=True)),
                ('what_are_we_not_delivering', models.TextField(blank=True, null=True)),
                ('target_audience', models.TextField(blank=True, null=True)),
                ('technologies', models.TextField(blank=True, null=True)),
                ('functionalities', models.TextField(blank=True, null=True)),
                ('tools', models.TextField(blank=True, null=True)),
                ('data_storing_requirements', models.TextField(blank=True, null=True)),
                ('restrictions', models.TextField(blank=True, null=True)),
                ('confidentiality', models.TextField(blank=True, null=True)),
                ('how_many_people_use_this', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
