# Generated by Django 4.0.4 on 2022-06-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='type',
            field=models.CharField(choices=[('main', 'Main'), ('additional', 'Additional')], default='main', max_length=24),
        ),
    ]
