# Generated by Django 4.0.4 on 2022-07-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_feature_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='plan_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
