# Generated by Django 4.0.4 on 2022-07-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_rename_name_client_first_name_alter_feature_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientProduct',
            new_name='ClientFeature',
        ),
    ]
