# Generated by Django 4.0.4 on 2022-06-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_service_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='product',
            field=models.ManyToManyField(related_name='%(class)ss', through='clients.ClientProduct', to='clients.feature'),
        ),
    ]
