# Generated by Django 4.0.4 on 2022-07-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_rename_clientproduct_clientfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='client_profiles'),
        ),
    ]
