# Generated by Django 4.0.4 on 2022-06-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='product',
            new_name='features',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='service',
            new_name='services',
        ),
    ]
