# Generated by Django 4.0.4 on 2022-07-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='hear_about_us',
            field=models.CharField(blank=True, choices=[('search_engine', 'Search Engine'), ('google_ads', 'Google Ads'), ('facebook_ads', 'Facebook Ads'), ('instagram_ads', 'Instagram Ads'), ('youtube_ads', 'Youtube Ads'), ('linkedin_ads', 'Linkedin Ads'), ('snapchat_ads', 'Snapchat Ads'), ('twitter_ads', 'Twitter Ads'), ('tiktok_ads', 'Tiktok Ads'), ('other_social_media_ads', 'Other Social Media Ads'), ('email', 'Email'), ('radio', 'Radio'), ('tv', 'Tv'), ('newspaper', 'Newspaper'), ('word_of_mouth', 'Word Of Mouth'), ('other', 'Other')], max_length=64, null=True),
        ),
    ]
