# Generated by Django 4.0.4 on 2022-06-28 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_rename_product_client_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
    ]
