# Generated by Django 4.0.4 on 2022-07-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_priceplan_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='priceplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='priceplan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='priceplan',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='priceplan',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='priceplan',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='priceplan',
            name='updated_by',
        ),
    ]
