# Generated by Django 4.0.4 on 2022-07-18 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_feature_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='clients.product'),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_plans', to='clients.feature'),
        ),
    ]
