# Generated by Django 4.0.4 on 2022-07-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_feature_product_alter_priceplan_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceplan',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
