# Generated by Django 4.0.4 on 2022-07-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_priceplan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
