# Generated by Django 4.0.4 on 2022-07-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_priceplan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='data_storing_requirements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='functionalities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='goals_and_expectation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='restrictions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='technologies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='tools',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
