# Generated by Django 4.0.4 on 2022-08-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_alter_requirement_data_storing_requirements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='project_timeline',
        ),
        migrations.AddField(
            model_name='requirement',
            name='project_timeline_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='project_timeline_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
