# Generated by Django 4.0.4 on 2022-08-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_remove_requirement_project_timeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='target_gender',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
