# Generated by Django 4.0.4 on 2022-08-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_requirement_target_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='target_age',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
