# Generated by Django 4.0.4 on 2022-04-24 06:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('p_start_date', models.DateTimeField(blank=True, null=True)),
                ('p_end_date', models.DateTimeField(blank=True, null=True)),
                ('a_start_date', models.DateTimeField(blank=True, null=True)),
                ('a_end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('issue_faced', 'Issue Faced'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=24)),
                ('projects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
        ),
    ]
