# Generated by Django 4.0.4 on 2022-04-24 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('very_important', 'Very Important'), ('important', 'Important'), ('normal', 'Normal'), ('less_important', 'Less Important')], default='normal', max_length=24),
        ),
        migrations.AddField(
            model_name='tasks',
            name='type',
            field=models.CharField(choices=[('dependent', 'Dependent'), ('independent', 'Independent')], default='independent', max_length=24),
        ),
        migrations.AddField(
            model_name='tasks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('issue_faced', 'Very Important'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=24),
        ),
    ]
