# Generated by Django 4.0.4 on 2022-04-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_deleted_at_alter_project_created_at_and_more'),
        ('tasks', '0002_tasks_created_at_tasks_deleted_at_tasks_priority_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
