# Generated by Django 4.0.4 on 2022-04-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_comments_comment_rename_projects_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='progress',
            field=models.IntegerField(),
        ),
    ]
