# Generated by Django 4.0.4 on 2022-07-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sub_stage',
        ),
    ]
