# Generated by Django 4.0.4 on 2022-06-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
