# Generated by Django 4.0.4 on 2022-04-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_usertask_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task'),
        ),
    ]
