# Generated by Django 4.0.4 on 2022-06-20 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(
                100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
