# Generated by Django 4.0.4 on 2022-07-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_sub_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('stage', 'Stage'), ('sub_stage', 'Sub Stage'), ('task', 'Task')], default='task', max_length=24),
        ),
    ]
