# Generated by Django 4.0.4 on 2022-06-18 04:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_alter_usertask_progress_alter_usertask_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together={('task', 'user')},
        ),
    ]
