# Generated by Django 4.0.4 on 2022-04-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_commentattachments_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentAttachments',
        ),
    ]
