# Generated by Django 4.0.4 on 2022-05-18 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
