# Generated by Django 4.0.4 on 2022-06-23 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_substage_task'),
        ('tasks', '0007_task_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sub_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='projects.substage'),
        ),
    ]
