# Generated by Django 4.0.4 on 2022-05-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_task_a_end_date_alter_task_a_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('issue_faced', 'Issue Faced'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=24),
        ),
    ]
