# Generated by Django 4.0.4 on 2022-05-29 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0016_reminder_remind_at'),
        ('tasks', '0012_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_users',
            field=models.ManyToManyField(related_name='users', through='tasks.UserTask', to=settings.AUTH_USER_MODEL),
        ),
    ]
