# Generated by Django 4.0.4 on 2022-05-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_task_task_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='deleted_at',
        ),
    ]
